- docs/apm-configuration/java/java-apm-setup.mdx
- docs/apm-configuration/java/java-overview.mdx
1. Added feature list
2. Added release link
3. Updated JAR with the latest version
> java doc update

- docs/agent-installation/host-agent.mdx
- docs/agent-installation/kubernetes/auto-instrumentation-in-kubernetes.mdx
- docs/agent-installation/troubleshooting.mdx
Made some small changes to intro paragraphs as well as some grammatical edits. Wanted to make my first PR small to make sure it looks alright.
> small structural changes

- docs/apm-configuration/dotnet/dotnet-apm-setup.mdx
- mint.json
> [dotnet-apm-setup]: Added the doc for dotnet apm setup

- docs/apm-configuration/ruby/ruby-apm-setup.mdx
- docs/apm-configuration/ruby/ruby-overview.mdx
- mint.json
Added the documentation for Ruby integration
> Added the Ruby doc

- docs/apm-configuration/dotnet/dotnet-overview.mdx
- mint.json
> Added the documentation of dotnet overview page

- docs/agent-installation/docker.mdx
- docs/agent-installation/kubernetes.mdx
- docs/agent-installation/linux.mdx
Changing period to colon in Docker Uninstall section.
> Grammar fixes

- docs/agent-installation/docker.mdx
- docs/agent-installation/kubernetes.mdx
- docs/agent-installation/linux.mdx
Working with Zach to make sure I dont ruin the Docs!
> small test/edit

- docs/agent-installation/docker.mdx
- docs/rum/getting-started.mdx
Add step to RUM setup page to create application reference on middleware installation page
> RUM add step to create application

- docs/agent-installation/docker.mdx
Small changes. Move the Overview title and make a few wording adjustments.
> Docker Agent Install, move title and clarify agent name

- docs/apm-configuration/next-js.mdx
> Vercel fix

- integrations/prometheus-integration-k8s.mdx
- mint.json
Reverts middleware-dev/docs#137
> Revert "Adding prometheus-k8s doc to integrations section in sidebar"

- apm-configuration/dotnet.mdx
Reverts middleware-dev/docs#138
> Revert "fixing typo in .NET doc"

- agent-installation/docker.mdx
- agent-installation/kubernetes.mdx
- agent-installation/linux.mdx
- agent-installation/windows.mdx
- apm-configuration/cloudflare.mdx
- apm-configuration/dotnet.mdx
- apm-configuration/go.mdx
- apm-configuration/java.mdx
- apm-configuration/next-js.mdx
- apm-configuration/node-js.mdx
- apm-configuration/php.mdx
- apm-configuration/python.mdx
- apm-configuration/ruby.mdx
- apm-configuration/vercel-integration.mdx
- data-ingestion-apis/opentelemetry-metrics.mdx
- integrations/elasticsearch-integration.mdx
- integrations/jira-integration.mdx
- integrations/kinesis-streams.mdx
- integrations/microsoft-team-integration.mdx
- integrations/mongodb-integration.mdx
- integrations/mysql-integration.mdx
- integrations/opsgenie-integration.mdx
- integrations/pagerduty-integration.mdx
- integrations/postgresql-integration.mdx
- integrations/prometheus-integration.mdx
- integrations/redis-integration.mdx
- integrations/slack-integration.mdx
- mint.json
- rum/getting-started.mdx
Fixing MW Agent section of Getting Started. Made titles and headers consistent
> Style Fixes

- mint.json
- workflow/profiling.mdx
Rough draft for the Continuous Profiling document.
> Continuous Profiling

- apm-configuration/node-js.mdx
fixing quotes in Node.js code snippet
> Node.js hot fix

- rum/getting-started.mdx
Making Install process for trace propogation more explicit
> RUM Hotfix

- apm-configuration/cloudflare.mdx
- apm-configuration/dotnet.mdx
- apm-configuration/go.mdx
- apm-configuration/java.mdx
- apm-configuration/next-js.mdx
- apm-configuration/node-js.mdx
- apm-configuration/php.mdx
- apm-configuration/python.mdx
- apm-configuration/ruby.mdx
- apm-configuration/vercel-integration.mdx
Minor changes for consistency across APM pages
> Fixing APM Intro + Prereqs

- apm-configuration/apm_overview.mdx
- apm-configuration/cloudflare.mdx
- apm-configuration/dotnet.mdx
- apm-configuration/go.mdx
- apm-configuration/java.mdx
- apm-configuration/next-js.mdx
- apm-configuration/node-js.mdx
- apm-configuration/php.mdx
- apm-configuration/python.mdx
- apm-configuration/ruby.mdx
- apm-configuration/vercel-integration.mdx
Tentative location for the Profiling Support table. 
Need to add all APMs to this table + references for all APMs
> Profiling Support Table

- integrations/cassandra-integration.mdx
Changed the second sentence of the first paragraph to shed more detail on how it works. We should aim to do this for all pages. 
The closing lines of "Quickly pinpoint bottlenecks and optimize..." are marketing sentences. They don't actually tell the user anything informational.
Also added one small comment in step 2 to help call out how those hosts appear. I've seen users get tripped up on that.
> small edits to help the flow

- agent-installation/kubernetes.mdx
- apm-configuration/php.mdx
- Converting last step in prerequisites into the first step in install. 
- Making the steps throughout install page more clear
- separating docker and kubernetes container setup
> PHP Install Cleanup

- agent-installation/kubernetes.mdx
What is the command to check if a MW Kubernetes agent is already installed and command to remove it?
This will be helpful for users that might choose to abandon the original install process.
> K8s MS Powershell Install

- mint.json
- release-notes/release-2.mdx
> Release Notes: Feb 13

- rum/getting-started.mdx
Adding RUM patterns to guide section + Notes for browser RUM
> RUM Patterns + Notes

- apm-configuration/dotnet.mdx
Adding custom logs section to docs + minor fixes across rest of doc.
> .NET Update

- mint.json
- release-notes/release-3.mdx
Kafka Integration link is not included in this document because integration setup has not been provided yet.
> February 28th Release Notes

- agent-installation/mesos/monitoring-mesos-slaves.mdx
- agent-installation/windows.mdx
- apm-configuration/next-js/next.js-apm-setup.mdx
- apm-configuration/python/python-apm-setup.mdx
- apm-configuration/vercel-integration.mdx
- docs/apm-configuration/next-js/vercel-integration.mdx
- rum/installation.mdx
- serverless/aws-lambda.mdx
Reverts middleware-dev/docs#273
> Revert "docs link update"

- mint.json
- release-notes/release-5.mdx
This release covers all changes made between May 21 and April 24
> Release Note #5

- apm-configuration/deno.mdx
- Update Deno package version
- Include Hono framework example
> Update Deno apm docs
